-- Change VARCHAR and VARCHAR(256) to TEXT in "auditLog" table
ALTER TABLE auditLog
ALTER COLUMN id TYPE TEXT USING CAST(id AS TEXT),
ALTER COLUMN serverid TYPE TEXT USING CAST(serverid AS TEXT),
ALTER COLUMN type TYPE TEXT USING CAST(type AS TEXT),
ALTER COLUMN moderatorId TYPE TEXT USING CAST(moderatorId AS TEXT),
ALTER COLUMN userId TYPE TEXT USING CAST(userId AS TEXT),
ALTER COLUMN removedRoles TYPE TEXT[] USING CAST(removedRoles AS TEXT[]),
ALTER COLUMN channel TYPE TEXT USING CAST(channel AS TEXT);