-- Change VARCHAR and VARCHAR(256) to TEXT in "auditLogs" table
ALTER TABLE auditLogs
ALTER COLUMN id TYPE TEXT USING CAST(id AS TEXT),
ALTER COLUMN serverid TYPE TEXT USING CAST(serverid AS TEXT),
ALTER COLUMN type TYPE TEXT USING CAST(type AS TEXT),
ALTER COLUMN channelids TYPE TEXT[] USING CAST(channelids AS TEXT[]);